/**
 * Independent mathematical verification of the Arud circle model.
 *
 * Everything here is recomputed by brute force — string comparison over
 * all rotations, explicit subgroup closure checks, letter counting —
 * deliberately NOT reusing sequencePeriod/stabilizerOrder/parseMeterPattern
 * internals, so agreement between this script and the app is meaningful.
 *
 * Run: npx vite-node scripts/verify-math.ts
 */
import { ALL_CIRCLES, TAFILA_MAP, parseMeterPattern } from '../constants';
import { CIRCLE_ROTATIONS, sequencePeriod, stabilizerOrder } from '../data/rotations';
import { tokenizeArudScript } from '../utils/scansion';

let checks = 0;
let failures = 0;

const assert = (cond: boolean, label: string) => {
  checks += 1;
  if (!cond) {
    failures += 1;
    console.error(`  ✗ FAIL: ${label}`);
  }
};

const rotate = <T,>(arr: T[], k: number): T[] =>
  arr.map((_, i) => arr[(i + k) % arr.length]);

const gcd = (a: number, b: number): number => (b === 0 ? a : gcd(b, a % b));

console.log('═══ Independent verification of the Arud circle mathematics ═══\n');

// ── 1. Rotation-group facts, brute force per circle ─────────────────────
console.log('1. Cyclic action, orbit, and stabilizer (brute force)');
const summary: { name: string; n: number; orbit: number; stab: number; used: number; muhmal: number }[] = [];

for (const circle of ALL_CIRCLES) {
  const seq = circle.atomicSequence;
  const n = seq.length;

  // Brute-force orbit: distinct rotations as strings
  const rotationStrings = Array.from({ length: n }, (_, k) => rotate(seq, k).join(','));
  const orbitBF = new Set(rotationStrings).size;

  // Brute-force stabilizer: the set of k that fix the sequence
  const fixers = Array.from({ length: n }, (_, k) => k).filter(
    (k) => rotationStrings[k] === rotationStrings[0]
  );
  const stabBF = fixers.length;

  // (a) matches the app's computations
  assert(orbitBF === sequencePeriod(seq), `${circle.id}: brute-force orbit = sequencePeriod`);
  assert(stabBF === stabilizerOrder(seq), `${circle.id}: brute-force stabilizer = stabilizerOrder`);

  // (b) orbit–stabilizer theorem
  assert(orbitBF * stabBF === n, `${circle.id}: |orbit|·|stab| = n (${orbitBF}·${stabBF} = ${n})`);

  // (c) the fixers really form a subgroup of Z/nZ: closed, has identity, inverses
  assert(fixers.includes(0), `${circle.id}: stabilizer contains identity`);
  for (const a of fixers)
    for (const b of fixers)
      assert(fixers.includes((a + b) % n), `${circle.id}: stabilizer closed under +`);
  for (const a of fixers)
    assert(fixers.includes((n - a) % n), `${circle.id}: stabilizer closed under inverse`);

  // (d) it is the cyclic subgroup generated by the period
  const p = n / stabBF;
  assert(
    fixers.join(',') === Array.from({ length: stabBF }, (_, i) => i * p).join(','),
    `${circle.id}: stabilizer = ⟨rotation by ${p}⟩ ≅ C_${stabBF}`
  );

  // (e) rotation table agrees with brute-force equivalence
  const rotTable = CIRCLE_ROTATIONS[circle.id];
  for (let i = 0; i < n; i++) {
    const info = rotTable[i];
    const canon = info.kind === 'duplicate' ? info.of : i;
    for (let j = 0; j < n; j++) {
      const jInfo = rotTable[j];
      const jCanon = jInfo.kind === 'duplicate' ? jInfo.of : j;
      const sameString = rotationStrings[i] === rotationStrings[j];
      // NB: same rotation string ⇒ same canonical entry, and vice versa,
      // only when parsing instructions coincide — at the unit level they do.
      assert(
        sameString === (canon === jCanon),
        `${circle.id}: rotations ${i},${j} equivalence matches table`
      );
    }
  }

  // (f) star figure of the stabilizer generator: chords i→i+p decompose
  // into gcd(n,p) = p closed cycles, each of length n/p = |stabilizer|
  if (p < n) {
    const seen = new Set<number>();
    let cycles = 0;
    for (let start = 0; start < n; start++) {
      if (seen.has(start)) continue;
      cycles += 1;
      let cur = start;
      let len = 0;
      do {
        seen.add(cur);
        cur = (cur + p) % n;
        len += 1;
      } while (cur !== start);
      assert(len === stabBF, `${circle.id}: star cycle length = |stabilizer|`);
    }
    assert(cycles === gcd(n, p) && cycles === p, `${circle.id}: star {${n}/${p}} has ${p} components`);
  }

  const used = rotTable.filter((r) => r.kind === 'meter').length;
  const muhmal = rotTable.filter((r) => r.kind === 'muhmal').length;
  assert(used + muhmal === orbitBF, `${circle.id}: used + neglected = orbit size`);
  summary.push({ name: circle.name, n, orbit: orbitBF, stab: stabBF, used, muhmal });
  console.log(
    `  ✓ ${circle.id}: n=${n}, orbit=${orbitBF}, stabilizer=C_${stabBF}, ` +
      `${used} used + ${muhmal} neglected — theorem holds`
  );
}

const totalUsed = summary.reduce((s, c) => s + c.used, 0);
const totalMuhmal = summary.reduce((s, c) => s + c.muhmal, 0);
const totalOrbits = summary.reduce((s, c) => s + c.orbit, 0);
assert(totalUsed === 16, 'exactly 16 canonical meters');
assert(totalMuhmal === 5, 'exactly 5 neglected rotations');
assert(totalOrbits === 21, '21 distinct rotations in total');
console.log(`  ✓ global: ${totalOrbits} distinct rotations = ${totalUsed} used + ${totalMuhmal} neglected\n`);

// ── 2. Meter patterns re-derived independently of parseMeterPattern ─────
console.log('2. Tafila patterns re-derived from TAFILA_MAP directly');
const PREFIX: Record<string, string> = {
  'circle1-mixed': '',
  'circle2-pure': 'c2:',
  'circle3-contracted': 'c3:',
  'circle4-accordant': 'c6:',
  'circle5-consonant': 'c5:',
};
for (const circle of ALL_CIRCLES) {
  for (const meter of circle.meters) {
    // Independent grouping walk
    const derived: string[] = [];
    let cursor = meter.startOffset;
    for (const size of meter.parsingInstructions) {
      const group = Array.from(
        { length: size },
        (_, i) => circle.atomicSequence[(cursor + i) % circle.atomicSequence.length]
      ).join(',');
      const entry = TAFILA_MAP[PREFIX[circle.id] + group] ?? TAFILA_MAP[group];
      assert(!!entry, `${meter.id}: TAFILA_MAP covers group "${group}"`);
      derived.push(entry?.merged ?? '?');
      cursor += size;
    }
    const app = parseMeterPattern(meter, circle).map((t) => t.merged);
    // Circle 3 is special-cased in the app; both routes must agree
    assert(
      derived.join(' ') === app.join(' '),
      `${meter.id}: independent derivation = app parse (${derived.join(' ')} vs ${app.join(' ')})`
    );
  }
}
console.log('  ✓ all 16 meters: independent TAFILA_MAP walk = app parse\n');

// ── 3. The two named neglected meters match their classical patterns ────
console.log('3. Classical identities of the named neglected rotations');
const circle1 = ALL_CIRCLES.find((c) => c.id === 'circle1-mixed')!;
const derive = (offset: number, instructions: number[]): string => {
  const out: string[] = [];
  let cur = offset;
  for (const size of instructions) {
    const g = Array.from(
      { length: size },
      (_, i) => circle1.atomicSequence[(cur + i) % circle1.atomicSequence.length]
    ).join(',');
    out.push(TAFILA_MAP[g]?.merged ?? '?');
    cur += size;
  }
  return out.join(' ');
};
assert(
  derive(2, [3, 2, 3, 2]) === 'مفاعيلن فعولن مفاعيلن فعولن',
  'المستطيل (offset 2) = مفاعيلن فعولن مفاعيلن فعولن'
);
assert(
  derive(4, [2, 3, 2, 3]) === 'فاعلن فاعلاتن فاعلن فاعلاتن',
  'الممتد (offset 4) = فاعلن فاعلاتن فاعلن فاعلاتن'
);
console.log('  ✓ المستطيل and الممتد match their classical tafila sequences\n');

// ── 4. Letter/mora arithmetic and scansion alignment ────────────────────
console.log('4. Letter arithmetic: units ↔ prosodic writing');
// The canonical template governs the theoretical form. In real verse the
// FIRST hemistich (ṣadr) usually realizes it exactly, while the SECOND
// (ʿajuz) may legally deviate in its final foot (ḍarb) through classical
// ʿilal such as qaṭʿ — so first-hemistich exactness is what we assert;
// both-hemistich exactness is reported as a statistic.
let sadrExact = 0;
let bothExact = 0;
const sadrDeviations: string[] = [];
for (const circle of ALL_CIRCLES) {
  for (const meter of circle.meters) {
    // Template letters per hemistich = Σ unit string lengths over the span
    let cursor = meter.startOffset;
    let template = 0;
    for (const size of meter.parsingInstructions) {
      for (let i = 0; i < size; i++) {
        template += circle.atomicSequence[(cursor + i) % circle.atomicSequence.length].length;
      }
      cursor += size;
    }
    const script = meter.famousExamples[0]?.arudScript;
    assert(!!script, `${meter.id}: has arudScript`);
    const halves = (script ?? '').split('***').map((h) => tokenizeArudScript(h.trim()).length);
    if (halves[0] === template) sadrExact += 1;
    else sadrDeviations.push(`${meter.id} (template ${template}, ṣadr ${halves[0]})`);
    if (halves[0] === template && (halves[1] ?? template) === template) bothExact += 1;
  }
}
assert(sadrExact === 14, `14 of 16 first hemistichs letter-perfect (got ${sadrExact})`);
assert(
  sadrDeviations.length === 2 &&
    sadrDeviations.every((d) => d.startsWith('al-basit') || d.startsWith('al-mutadarik')),
  'ṣadr deviations are exactly al-basit (khabn) and al-mutadarik (khabab form)'
);
console.log(`  ✓ ṣadr letter-perfect: ${sadrExact}/16 (deviations: ${sadrDeviations.join('; ')})`);
console.log(`  ✓ both hemistichs letter-perfect: ${bothExact}/16 — remaining ʿajuz`);
console.log('    deviations are classical ḍarb variations (qaṭʿ etc.), as expected\n');

// ── Result ───────────────────────────────────────────────────────────────
console.log('═'.repeat(64));
if (failures === 0) {
  console.log(`ALL ${checks} CHECKS PASSED — the mathematics is internally`);
  console.log('consistent and matches the classical system.');
} else {
  console.error(`${failures} of ${checks} checks FAILED`);
  process.exit(1);
}
